[test]
preload = [ "./happydom.ts" ]
coverage = true
coverageReporter = [
  "text",
  "lcov",
]
coverageDir = "coverage"
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "happydom.ts",
  "src/browser.ts"
]
coverageThreshold = { lines = 0.85, functions = 0.9 }
